# Server
SPRING_PROFILES_ACTIVE: qa
CONTAINER_PORT: ${CONTAINER_PORT}
CONTAINER_HOST: ${CONTAINER_HOST}
HOST_PORT: ${HOST_PORT}
CALLBACK_HOST: ${CALLBACK_HOST}

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOSTNAME}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin&retryWrites=false

# Database connection
MONGO_PORT: ${MONGO_PORT}
MONGO_HOSTNAME: ${MONGO_HOSTNAME}
MONGO_DATA_HOST_PATH: ${MONGO_DATA_HOST_PATH}
MONGO_LOG_HOST_PATH: ${MONGO_LOG_HOST_PATH}
MONGO_INITDB_SCRIPTS_HOST_PATH: ${MONGO_INITDB_SCRIPTS_HOST_PATH}
MONGO_AUTO_INDEX_CREATION: ${MONGO_AUTO_INDEX_CREATION}
MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}

# TWILIO
ACCOUNT_SID: ${ACCOUNT_SID}
AUTH_TOKEN: ${AUTH_TOKEN}
TWILIO_NUMBER: ${TWILIO_NUMBER}
TEST_AUTH_TOKEN: ${TEST_AUTH_TOKEN}
TEST_ACCOUNT_SID: ${TEST_ACCOUNT_SID}
USE_TEST_ACCOUNT: false
POLL_FOR_STATUS: ${POLL_FOR_STATUS}
SCHEDULING_SMS_SID: ${SCHEDULING_SMS_SID}
BULK_SMS_SID: ${BULK_SMS_SID}
