server:
  port: ${CONTAINER_PORT:8080}
  address: ${CONTAINER_HOST:localhost}

spring:
  application:
    name: sms-management-service
    cloud:
      loadbalancer:
        ribbon:
          enabled: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOSTNAME}:${MONGO_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin&retryWrites=false

twilio:
  accountSid: ${ACCOUNT_SID}
  authToken: ${AUTH_TOKEN}
  testAccountSid: ${TEST_ACCOUNT_SID}
  testAuthToken: ${TEST_AUTH_TOKEN}
  useTestAccount: ${USE_TEST_ACCOUNT:true}
  number: ${TWILIO_NUMBER}
  service:
    schedulingSMSSid: ${SCHEDULING_SMS_SID}
    bulkSMSSid: ${BULK_SMS_SID}
  callback:
    url: ${CALLBACK_HOST}/api/v1/provider/callback
    endpoints:
      smsStatus: /message-status
      inboundMessage: /inbound-message