server:
  port: ${CONTAINER_PORT:8080}
  address: ${CONTAINER_HOST:localhost}

spring:
  application:
    name: sms-management-service
    cloud:
      loadbalancer:
        ribbon:
          enabled: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_HOSTNAME}:${MONGO_CONTAINER_PORT}/${MONGO_INITDB_DATABASE}?authSource=admin

twilio:
  accountSid: ${ACCOUNT_SID}
  authToken: ${AUTH_TOKEN}
  trialNumber: ${TRIAL_NUMBER}
  pollForStatus: ${POLL_FOR_STATUS:true}
  service:
    schedulingSMSSid: ${SCHEDULING_SMS_SID}
    bulkSMSSid: ${BULK_SMS_SID}

app:
  callback:
    url: ${CALLBACK_HOST}/api/v1/callback
    endpoints:
      smsStatus: /sms-status
      health: /health